name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      
    - name: Install dependencies
      run: |
        dart pub global activate melos
        melos bootstrap
      
    - name: Build Web
      run: |
        cd apps/mobile
        flutter build web --release --base-href /brain-exploder/
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/mobile/build/web
